---
output:
  md_document:
    variant: markdown_github
---

# Purpose

The aim of this folder is to.... (Explain yourself here)

Load in coding scripts

```{r}
library(readxl)
library(data.table)
#loading data
library(data.table)
setwd("C:/Users/Andre/Documents/Testing uploading/Testing uploading/data/Happy")
files<-list.files(pattern = ".csv")
temp<-lapply(files, fread, sep=",")
data<-rbindlist(temp)
```



```{r}
data %>% 
  select("Country name", "Regional indicator")



```

# Data loading

Loading in some really crucial data here, and then producing a beautiful plot:

```{r}

df_flowers <- read_rds('data/flowers.rds')

ggplot(df_flowers) +
    geom_point(aes(Petal.Length, Petal.Width, color = Species) ) +
               labs(title = 'Amazing plot', y = 'petal widths', x = 'petal lengths')

```

# Lastly

* Notice that the 'bin' folder is used for binary files (pdfs, word docs, etc)

* 'settings' folder should be used only for human readable files that are used as user input settings files.

